/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/@lgs/AppHeader/AppHeader.vue')['default']
    BindPhone: typeof import('./src/components/@lgs/BindPhone/BindPhone.vue')['default']
    DatePicker: typeof import('./src/components/@lgs/PickerDate/DatePicker.vue')['default']
    DragView: typeof import('./src/components/@lgs/DragView/DragView.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Loading: typeof import('./src/components/@lgs/Loading/Loading.vue')['default']
    MapLocation: typeof import('./src/components/@lgs/MapLocation/MapLocation.vue')['default']
    NoData: typeof import('./src/components/@lgs/NoData/NoData.vue')['default']
    NotWeixin: typeof import('./src/components/@lgs/NotWeixin/NotWeixin.vue')['default']
    PickerAddress: typeof import('./src/components/@lgs/PickerAddress/PickerAddress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('./src/components/@lgs/Stepper/Stepper.vue')['default']
    TabBar: typeof import('./src/components/@lgs/TabBar/TabBar.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
